version: '3.7'
services:
  blog-sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: My_Password
      ACCEPT_EULA: Y
